---
title: "Introduction to michigancolors"
author: "Andrew Grogan-Kaylor"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to michigancolors}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE, echo=FALSE}

knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE, 
                      collapse = TRUE, 
                      comment = "#>")

```

# Introduction

This package provides a color palette for University of Michigan colors that can be used in R graphs.

# Installation

```{r}

devtools::install_github("agrogan1/michigancolors")

```

```{r}

library(michigancolors)

```


# Use

```{r}

# iris data set
 
data(iris)

```

## Base R

### Histograms
 
```{r}

hist(iris$Petal.Length, col = michigan_colors) 

```

```{r}

hist(iris$Petal.Length, col = arboretum_blue)

```

### Barplot

```{r}

barplot(table(iris$Species), 
        xlab = "Species", 
        ylab = "Frequency",
        col = michigan_colors,
        main = "Species Type in Iris Data Set")

```

### Scatterplots

```{r}

plot(iris$Sepal.Length, 
     iris$Petal.Length,
     bg = michigan_colors,
     pch = 21,
     main = "Scatterplot of Iris Data Set")

```

```{r}

plot(iris$Sepal.Length, 
     iris$Petal.Length,
     bg = arboretum_blue,
     pch = 21,
     main = "Scatterplot of Iris Data Set")

```

### Boxplot

```{r}

boxplot(Sepal.Length ~ Species, 
        ylab = "Sepal Length",
        data = iris,
        main = "Boxplot of Iris Data", 
        col = michigan_colors)

```

## ggplot2

```{r}

library(ggplot2)

```

### Density Plot

```{r}

ggplot(iris,
       aes(x=Petal.Length,
           fill = Species)) +
         geom_density() +
  facet_wrap(~Species) +
  ggtitle("Petal Length in Different Species of Iris") +
  theme_minimal() +
  scale_fill_manual(values = michigan_colors)

```

### Scatterplot with Smoother

```{r}

ggplot(iris,
       aes(x = Petal.Length,
           y = Sepal.Length,
           color = Species)) + 
  geom_point() + 
  geom_smooth() +
  ggtitle("Scatterplot of Iris Data Set") +
  theme_minimal() +
  scale_color_manual(values = michigan_colors)

```


